jobs:
- job: BuildLintUnitTest
  displayName: Build, Lint and Unit Test
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - bash: echo Hello World
- job: BuildLintUnitTestAndTag
  displayName: Build, Lint, Unit Test and Tag
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - bash: "echo This is amazing!

#- stage: ContainerizeAndIntegrationTests
#  dependsOn: BuildAndUnitTest
#  condition: succeeded()
#  jobs:
#  - job: BuildContainer
#    pool:
#      vmImage: 'Ubuntu-16.04'
#    steps:
#    - script: echo Building Container
#  - job: IntegrationTests
#    dependsOn: BuildContainer
#    condition: succeeded()
#    pool:
#      vmImage: 'Ubuntu-16.04'
#    steps:
#    - script: echo Integration Tests
#  - job: StoreContainer
#    dependsOn: IntegrationTests
#    condition: succeeded()
#    pool:
#      vmImage: 'Ubuntu-16.04'
#    steps:
#    - script: echo Deploying container
#- stage: DeployToStaging
#  dependsOn: ContainerizeAndIntegrationTests
#  condition: succeeded()
#  jobs:
#  - job: DeployToStaging
#    pool:
#      vmImage: 'Ubuntu-16.04'
#    steps:
#    - script: echo Deploying to Staging
