stages:
- stage: Commit
  jobs:
  - job: BuildLintUnitTest
    displayName: Build, Lint and Unit Test
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - bash: echo Build, Lint and Test
- stage: Merge
  dependsOn: Commit
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/v')))
  jobs:
  - job: TagPR
    displayName: Tag Pull Request
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - bash: echo $(Build.SourceBranch)
- stage: MergeRelease
  dependsOn: Commit
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/v'))
  jobs:
  - job: TagPRRelease
    displayName: Tag Pull Request and Create Release
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - bash: echo $(Build.SourceBranch)
