stages:
- stage: Commit
  jobs:
  - job: BuildLintUnitTest
    displayName: Build, Lint and Unit Test
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - bash: echo Build, Lint and Test
- stage: Merge
  dependsOn: Commit
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: TagPR
    displayName: Tag Pull Request
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - bash: |
    echo $(Build.SourceBranch)
    echo $(System.PullRequest.SourceBranch)
